SchoolManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

admin.site.site_header = 'SCHOOL MANAGEMENT PORTAL'

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path('api/v1/', include('sms.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact')
]

sms/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import SimpleRouter, DefaultRouter

app_name = 'sms'

router = SimpleRouter()
router.register('students', views.StudentViewSet)
router.register('staffs', views.StaffViewSet)

urlpatterns = [
    path('api', include(router.urls))
]

pages/models.py
from django.db import models

# Create your models here.

sms/models.py
from django.db import models


# Create your models here.

class Student(models.Model):
    GENDER = (
        ('MALE', 'Male'),
        ('FEMALE', 'Female')
    )
    date_of_birth = models.DateField()
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    other_student_details = models.TextField(255)
    gender = models.CharField(choices=GENDER, max_length=6)


class Course_Scheduled(models.Model):
    course_offering_id = models.ForeignKey('Course_Offered', on_delete=models.CASCADE)
    other_course_schedule_details = models.TextField(max_length=255)


class Student_Course_Registrations(models.Model):
    course_schedule_id = models.ForeignKey(Course_Scheduled, on_delete=models.CASCADE, related_name='course_sch_id')
    student_course_registration = models.ForeignKey(Student, on_delete=models.CASCADE)


class Course_Offered(models.Model):
    course_offering_name = models.TextField(max_length=255)
    other_course_offering_details = models.TextField(max_length=255)


class Staff(models.Model):
    date_of_birth = models.DateField()
    first_name = models.TextField(max_length=255)
    last_name = models.TextField(max_length=255)
    job_title = models.TextField(max_length=255)
    phone_number = models.TextField(max_length=15)
    email_address = models.EmailField(unique=True)
    other_staff_details = models.TextField(max_length=255)


class Staff_Courses_Supervision(models.Model):
    staff_id = models.ForeignKey(Staff, on_delete=models.CASCADE)
    course_offering_id = models.ForeignKey(Course_Offered, on_delete=models.CASCADE)


class Staff_Research_Interests(models.Model):
    staff_id = models.ForeignKey(Staff, on_delete=models.CASCADE)
    area_of_research_id = models.ForeignKey('Research_Projects', on_delete=models.CASCADE)


class Research_Projects(models.Model):
    area_of_research_id = models.IntegerField()
    project_name = models.TextField(max_length=255)
    project_description = models.TextField(max_length=255)
    other_details = models.TextField(max_length=255)


class Staff_on_Research_Projects(models.Model):
    project_id = models.ForeignKey(Research_Projects, on_delete=models.CASCADE)
    staff_id = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date_from = models.DateField(primary_key=True)
    date_to = models.DateField()

pages/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, 'pages/index.html')


def about(request):
    return render(request, 'pages/about.html')


def contact(request):
    return render(request, 'pages/contact.html')

sms/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.response import Response

# Create your views here.
from sms.models import Student, Staff
from sms.serializer import StudentSerializer, StaffSerializer
from rest_framework.viewsets import ModelViewSet
from .models import Student, Staff


class StudentViewSet(ModelViewSet):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer


class StaffViewSet(ModelViewSet):
    queryset = Staff.objects.all()
    serializer_class = StaffSerializer

pages/templates/pages/about.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About SMS</title>
</head>
{% block content %}
<body>
    <h1>Welcome to SMS, the best way to manage your school</h1>
{% endblock %}
</body>
</html>

pages/templates/pages/contact.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact Us</title>
</head>
<body>
{% block content %}
    <h1>SMS contact page</h1>
    <p>You can reach us through our various channel </p>
{% endblock %}
</body>
</html>

pages/templates/pages/index.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'pages/css/index.css' %}">
    <title>Homepage</title>
</head>
<body>
{% block content %}
    <h1 style="color: red">Welcome to school management portal</h1>
{% endblock %}
</body>
</html>

sms/templates/sms/staff-details.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ staff.first_name }} {{ staff.last_name }} details</title>
</head>
<body>
{% block content %}
    <ul>
        <li>First Name: {{ staff.first_name }}</li>
        <li>Last Name: {{ staff.last_name }}</li>
        <li>Email: {{ staff.email_address }}</li>
        <li>Phone Number: {{ staff.phone_number }}</li>
        <li>Job Title: {{ staff.job_title }}</li>
        <li>Birth Date: {{ staff.date_of_birth }}</li>
        <li>Other Staff Details {{ staff.other_staff_details }} </li>
    </ul>
{% endblock %}
</body>
</html>

sms/templates/sms/staff-list.html
{% extends 'base.html' %}

    {% block content %}

        {% for staff in staffs %}
            <li><a href="{% url 'sms:students-details' pk=staff.pk %}">{{ staff.first_name }} {{ staff.last_name }}</a></li>
        {% endfor %}
    {% endblock %}

sms/templates/sms/student-detail.html
{% extends 'base.html' %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Student details page</title>
</head>
<body>
{% block content %}
    <h1>welcome to {{ student.first_name }} {{ student.last_name }} full details page</h1>
    <hr>
    <p>{{ student.first_name }}</p>
    <p>{{ student.middle_name }}</p>
    <p>{{ student.last_name }}</p>
    <p>{{ student.date_of_birth }}</p>
    <p>{{ student.GENDER }}</p>
    <p>{{ student.other_student_details }}</p>


    <a href="{% url 'sms:student-list' %}">Go back to student list page</a>
{% endblock %}
</body>
</html>

sms/templates/sms/student-list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Student List</title>
</head>
<body>
    <ul>
        {% for student in students %}
            <li><a href="{% url 'sms:students-details' pk=student.pk %}">{{ student.first_name }} {{ student.last_name }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

templates/base.html
{% load  static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>Document</title>
</head>
<body>
<div class="sms-nav">
        <a href="{% url 'pages:index' %}">Home</a>
        <a href="{% url 'sms:student-list' %}">Student</a>
        <a href="{% url 'sms:staff-list' %}">Staff</a>
        <a href="{% url 'pages:contact' %}">Contact us</a>
        <a href="{% url 'pages:about' %}">About us</a>
    </div>
    <hr>
{% block content %}
{% endblock %}
</body>
</html>